### ISSUE TITLE
Problems with connection

### ISSUE THREAD

**Issue by deanisiavega** [marcobjorge/ikamand#2]
iKamand is connected to my Wi-Fi network but web app won't open.

<img width="938" alt="Bildschirmfoto 2024-05-13 um 21 10 12" src="https://github.com/marcobjorge/ikamand/assets/48922357/f6efdfbc-cc91-426d-916e-59d7acaf0322">

**Comment by marcobjorge** [comment]
It seems like a python dependency missing - let me figure out what's missing and I'll update the ticket.

**Comment by marcobjorge** [comment]
@deanisiavega , can you please let me know what's your node version (`node --version`)?

While I try to reproduce your problem with the correct node version, can you also please:

(1) try clearing out the node cache and reinstall
```
npm cache clean --force
rm -Rf node_modules
npm install
npm install -g pm2
pm2 start index.js --name "ikamand" -- -i 192.168.178.32
```

(2) try the same thing but with node 14
```
nvm install 14
nvm use 14
npm cache clean --force
rm -Rf node_modules
npm install
npm install -g pm2
pm2 start index.js --name "ikamand" -- -i 192.168.178.32
```

Please note it's `... -i 192.168.178.32` without the HTTP protocol - not related to your problem, just the next problem you'd hit :).

**Comment by marcobjorge** [comment]
I've just recorded [this](https://asciinema.org/a/6FCkqlhXZL9X22bHDLmrq3HDt) starting fresh from a [linuxcontainers/debian-slim](https://github.com/linuxcontainers/debian-slim) image - do you see any relevant difference compared to what you are doing?

**Comment by deanisiavega** [comment]
@marcobjorge, may be it was my mistake. I tried to install it on my raspberry with my iobroker installation. After installation of ikamand my iobroker won't work. I just reinstall my raspberry again.
Now I will try it with Home Assistant version.

Currently my ikamand won't connect to my network.
I thought the problem was with the connection. So I tried to reconnect ikamand with my router.
After some tries ikamand won't connect to the router. The blue LED lights solid or flash slow but I can't see it in my router any more. 
Any idea how to connect the ikamand again?

Thanks

**Comment by marcobjorge** [comment]
There are 2 versions of ikamand - do you know which one you have? I have a v2 and have not tested with v1.

Do you know the encryption on your wi-fi? I have WPA1, WPA2 and I'm connecting ikamand to WPA1 - I think ikamand v2 does not support WPA3.

Finally, the instructions to connect your ikamand v2 to wifi (might work with v1):
1. Reset the iKamand (long press on the side button, the blue light will go into speed-flash)
2. Call the API to configure the wi-fi (see [here](https://github.com/marcobjorge/ikamand?tab=readme-ov-file#setup-ikamand-wifi))

**Comment by deanisiavega** [comment]
It seems I have v2. 

`rfw_version=2.0.56&env=v1-&MAC=2050E7519E4C&model_number=i0121-v2`


Encryption is WPA2
```
ssid=FRITZ!Box Gastzugang            &rssi=-39&security=WPA2_AES  &channel= 13&bssid=9A:9B:CB:
ssid=FRITZ!Box 7590                  &rssi=-37&security=WPA2_AES  &channel= 13&bssid=98:9B:CB:
ssid=FRITZ!Box Gastzugang            &rssi=-64&security=WPA2_AES  &channel=  1&bssid=3A:10:
ssid=FRITZ!Box Gastzugang            &rssi=-64&security=WPA2_AES  &channel=  1&bssid=2E:3A:
ssid=FRITZ!Box 7590                  &rssi=-65&security=WPA2_AES  &channel=  1&bssid=38:10:
ssid=FRITZ!Box 7590                  &rssi=-64&security=WPA2_AES  &channel=  1&bssid=2C:3A:
ssid=FRITZ!Box Gastzugang            &rssi=-68&security=WPA2_AES  &channel=  6&bssid=46:4E:
ssid=FRITZ!Box 7590                  &rssi=-65&security=WPA2_AES  &channel=  6&bssid=44:4E:
```

ikamand was connected to my network in the past. But now it doesn't want to anymore.

I have tried both methods  [here](https://github.com/ludekvodicka/ikamand) several times.
After I enter the SSID and password, the LED starts blinking slowly, but ikamand does not appear in the router.
I have no idea why.

My knowledge of coding is somewhat limited. What exactly do I need to do?

**Comment by marcobjorge** [comment]
I'm not sure I will be able to help you, but this is what I would try:
(1) Create a network on your router with WPA1 and see if that helps (I don't remember if WPA2 works well...there's a reason I'm using WPA1 but I don't remember)
(2) Create a network on your router without special characters (exclamation mark) - I've had some devices failing to connect b/c of this...

**Comment by deanisiavega** [comment]
I got it to work. Suddenly it connected to the router. 
Many thanks for your support.
